### PR TITLE
SDK

### PR DESCRIPTION
**Pull request by pr0n00gler**

### CODE REVIEW

**Review by foxpy — APPROVED** [review]
I didn't test anything, only looked at the code and it looks good overall.

**Comment by swelf19** [comment]
The same as before. About placing licenses headers policy. Some of the file have the header, some do not.
for example 
https://github.com/neutron-org/neutron-sdk/blob/chore/sdk-preparations/packages/neutron-sdk/src/interchain_queries/queries.rs
and next to it
https://github.com/neutron-org/neutron-sdk/blob/chore/sdk-preparations/packages/neutron-sdk/src/interchain_queries/register_queries.rs
is it ok?

**Comment by foxpy** [comment]
[Here](https://www.apache.org/licenses/LICENSE-2.0.html), Apache states that:

> Include a copy of the Apache License, typically in a file called LICENSE, in your work, and consider also including a NOTICE file that references the License.

>To apply the Apache License to specific files in your work, attach the following boilerplate declaration, replacing the fields enclosed by brackets "[]" with your own identifying information. (Don't include the brackets!) Enclose the text in the appropriate comment syntax for the file format. We also recommend that you include a file or class name and description of purpose on the same "printed page" as the copyright notice for easier identification within third-party archives.

Since all files in this repository are licensed as Apache 2.0, there is no reason to include declaration headers in source files, `LICENSE` and `NOTICE` files are sufficient.

**Review by foxpy — DISMISSED** [review]
Aside from aforementioned slightly weird licensing I don't see any issues. And I don't see any legal problems since all of our code is licensed as Apache 2.0 anyway, hence I am approving this PR.

**Review by foxpy — APPROVED** [review]

**Review by oopcode — APPROVED** [review]

**Pull request merged**
